// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s2.proto

#include "s2.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace CCC_1 {
PROTOBUF_CONSTEXPR T::T(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.ints_)*/0} {}
struct TDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TDefaultTypeInternal() {}
  union {
    T _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TDefaultTypeInternal _T_default_instance_;
}  // namespace CCC_1
static ::_pb::Metadata file_level_metadata_s2_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_s2_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_s2_2eproto = nullptr;
const ::uint32_t TableStruct_s2_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::CCC_1::T, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::CCC_1::T, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CCC_1::T, _impl_.ints_),
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 9, -1, sizeof(::CCC_1::T)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::CCC_1::_T_default_instance_._instance,
};
const char descriptor_table_protodef_s2_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\010s2.proto\022\005CCC_1\"\021\n\001T\022\014\n\004ints\030\001 \002(\005"
};
static ::absl::once_flag descriptor_table_s2_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_s2_2eproto = {
    false,
    false,
    36,
    descriptor_table_protodef_s2_2eproto,
    "s2.proto",
    &descriptor_table_s2_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_s2_2eproto::offsets,
    file_level_metadata_s2_2eproto,
    file_level_enum_descriptors_s2_2eproto,
    file_level_service_descriptors_s2_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_s2_2eproto_getter() {
  return &descriptor_table_s2_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_s2_2eproto(&descriptor_table_s2_2eproto);
namespace CCC_1 {
// ===================================================================

class T::_Internal {
 public:
  using HasBits = decltype(std::declval<T>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(T, _impl_._has_bits_);
  static void set_has_ints(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

T::T(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CCC_1.T)
}
T::T(const T& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CCC_1.T)
}

inline void T::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ints_){0}
  };
}

T::~T() {
  // @@protoc_insertion_point(destructor:CCC_1.T)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void T::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void T::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void T::Clear() {
// @@protoc_insertion_point(message_clear_start:CCC_1.T)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ints_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* T::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {

#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required int32 ints = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_ints(&has_bits);
          _impl_.ints_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* T::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {

  // @@protoc_insertion_point(serialize_to_array_start:CCC_1.T)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required int32 ints = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_ints(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CCC_1.T)
  return target;
}

::size_t T::ByteSizeLong() const {

// @@protoc_insertion_point(message_byte_size_start:CCC_1.T)
  ::size_t total_size = 0;

  // required int32 ints = 1;
  if (_internal_has_ints()) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_ints());
  }
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData T::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    T::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*T::GetClassData() const { return &_class_data_; }


void T::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<T*>(&to_msg);
  auto& from = static_cast<const T&>(from_msg);

  // @@protoc_insertion_point(class_specific_merge_from_start:CCC_1.T)
  GOOGLE_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_ints()) {
    _this->_internal_set_ints(from._internal_ints());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void T::CopyFrom(const T& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CCC_1.T)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool T::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void T::InternalSwap(T* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.ints_, other->_impl_.ints_);
}

::PROTOBUF_NAMESPACE_ID::Metadata T::GetMetadata() const {

  return ::_pbi::AssignDescriptors(
      &descriptor_table_s2_2eproto_getter, &descriptor_table_s2_2eproto_once,
      file_level_metadata_s2_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace CCC_1
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CCC_1::T*
Arena::CreateMaybeMessage< ::CCC_1::T >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CCC_1::T >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
